### ISSUE TITLE
Add web archive for facebook.com

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo-warc-tests#11]
#8

**Comment by tigercosmos** [comment]
@highfive: assign me

**Comment by asajeffrey** [comment]
You're on!

**Comment by asajeffrey** [comment]
@tigercosmos any progress?

**Comment by tigercosmos** [comment]
sorry for late. I am on the way!

**Comment by tigercosmos** [comment]
i run with 
```
$ proxychains4 ~/servo/mach run -r --certificate-path proxy-certs/pywb-ca.pem https://www.facebook.com/
[proxychains] config file found: /usr/local/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.12_1/lib/libproxychains4.dylib
```
and servo open Facebook.

which `/usr/local/etc/proxychains.conf`
```
http 127.0.0.1
```

another run
```
$ wb-manager init FB1
$ wayback --proxy FB1 --live --proxy-record --autoindex --port 8080
[Errno 2] No such file or directory: './config.yaml'
2018-02-23 04:02:10,372: [INFO]: Proxy recording into collection "FB1"
2018-02-23 04:02:10,383: [INFO]: Auto-Indexing Enabled on "/Users/tigercosmos/webback/collections", checking every 30 secs
2018-02-23 04:02:10,491: [INFO]: Starting Gevent Server on 8080
2018-02-23 04:02:10,492: [INFO]: Checking Collection: FB1
2018-02-23 04:02:40,494: [INFO]: Checking Collection: FB1
2018-02-23 04:03:10,501: [INFO]: Checking Collection: FB1
```

and cannot get the achieve?

**Comment by tigercosmos** [comment]
Another issue is, login and not login are very different on performance. I think the page after login is more important.

**Comment by asajeffrey** [comment]
When you play back the archive, you're doing it with:
```
wayback --proxy FB1 --port 8080
```
but not seeing anything when you browse to it in servo?

What happens if you browse to `http://localhost:8080/`?

**Comment by asajeffrey** [comment]
The problem with recording the page after login is that we need some way to do that without including any credentials in the archive.

**Comment by tigercosmos** [comment]
when I run `proxychains4 ~/servo/mach run -r --certificate-path proxy-certs/pywb-ca.pem https://www.facebook.com/`, the servo had rendered Facebook successfully.

and why `readme` "recording" and "testing" about `proxychains` command are the same?

**Comment by asajeffrey** [comment]
The difference between "recording" and "testing" is in how `wayback` is running, not in how 
Servo is running.

**Comment by tigercosmos** [comment]
I change port to 8321
when I run `wayback --proxy Example --port 8321`
and run proxychains to `http://localhost:8321/` get
<img width="363" alt="2018-02-23 4 52 07" src="https://user-images.githubusercontent.com/18013815/36563571-81a43804-1855-11e8-8ee9-80801fbd5cf9.png">

---

when I run 
```
wayback --proxy Facebook --live --proxy-record --autoindex --port 8321
```
and run 
```
 proxychains4 ~/servo/mach run -r --certificate-path proxy-certs/pywb-ca.pem http://www.facebook.com/
```
the page render well but wayback doesn't work

**Comment by asajeffrey** [comment]
After getting servo to render Facebook, can you try replaying the archive? Kill wayback, then restart it in playback mode:
```
wayback --proxy Facebook --port 8321
```
then run:
```
 proxychains4 ~/servo/mach run -r --certificate-path proxy-certs/pywb-ca.pem https://www.facebook.com/
```
Also, I just noticed that you were using http rather than https. Can you retry using https?
