### ISSUE TITLE
Add web archive for yahoo.com

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo-warc-tests#15]
#8

**Comment by Belwyyn** [comment]
I would like to do this.

**Comment by asajeffrey** [comment]
Go for it!

**Comment by asajeffrey** [comment]
@Belwyyn any progress?

**Comment by Belwyyn** [comment]
Hey @asajeffrey, Sorry about the long silence. Had some personal/family matters come up in the last week. I will be getting back on this asap and hope to have something for you soon. Thank you for checking in on me.

**Comment by asajeffrey** [comment]
No problem, life has a habit of getting in the way! Glad to hear you're on this.

**Comment by Belwyyn** [comment]
I submitted a merge request. Is it visible?

**Comment by jdm** [comment]
No. The "Pull requests" tab shows 0 open pull requests.

**Comment by asajeffrey** [comment]
I can see the commit in your fork of the repo https://github.com/Belwyyn/servo-warc-tests/commit/4fd63e650cfa3c02ccc061623b2f989fee6c7057 so you just need to make a PR out of it! https://help.github.com/articles/creating-a-pull-request/

**Comment by Belwyyn** [comment]
Ahh, a case of rookie mistakes in which I set up the pull request without actually clicking the big green button.

**Comment by asajeffrey** [comment]
Closed by #54.
