### ISSUE TITLE
REAME link to Servo Wiki

### ISSUE THREAD

**Issue by tigercosmos** [servo/servo-warc-tests#31]
https://github.com/servo/servo/wiki/Creating-and-viewing-WARC-web-archives-in-Servo

**Comment by tigercosmos** [comment]
@asajeffrey  could you modify Servo's Wiki to link it here? :)
Also, here's readme also need to link Servo' Wiki.

**Comment by asajeffrey** [comment]
Added the link from the wiki to here, if anyone wants to edit the README to link to the wiki that would be great!
