### ISSUE TITLE
Set up Homu

### ISSUE THREAD

**Issue by aneeshusa** [servo/servo-warc-tests#34]
Now that we have a `.travis.yml` file (thanks to #26), it would be nice to have Homu set up for this repository.

Instructions are at https://github.com/servo/servo/wiki/Adding-a-repo-to-Homu; note that you'll need someone with admin perms for some of the steps.

**Comment by asajeffrey** [comment]
I can do the steps that need admin permissions if anyone wants to help steer the PRs!
