### ISSUE TITLE
Add shell script linting for servo-warc-tests.sh

### ISSUE THREAD

**Issue by aneeshusa** [servo/servo-warc-tests#4]
While looking at [this failed run](http://build.servo.org/builders/linux-nightly/builds/586/steps/test/logs/stdio) (via [#servo](https://mozilla.logbot.info/servo/20180129#c14205975)), beyond the fix in #3, it also looks like there are some additional issues with the `servo-warc-tests.sh` shell script. The biggest ones are:

- lack of `set -o errexit` to cause the script to exit on failure instead of continuing (see how the log shows attempted access to `/warc-tests-2018-01-29.csv` and `/ARCHIVES` after the original realpath failure); `set -o nounset` and `set -o pipefail` also go in here
- opening the file in my editor, shellcheck reports a number of quoting issues

I'd reccommend at least running shellcheck and the servo shell script linter once manually, and additionally hooking up `servo-tidy` to this repo in CI. (Adding shellcheck into `servo-tidy` is tracked at https://github.com/servo/servo/issues/19898.)

cc @asajeffrey

**Comment by asajeffrey** [comment]
OK, fixed. What would be the easiest way to run the lint in CI? I could just run `shellcheck` on Travis, but it looks like you had something more in mind.

**Comment by aneeshusa** [comment]
I was recommending running the same `servo-tidy` that Servo has in this repo; https://github.com/servo/servo/issues/10636 has examples.
It wouldn't hurt to run shellcheck as well.
