### ISSUE TITLE
add CI service 

### ISSUE THREAD

**Issue by tigercosmos** [servo/servo-warc-tests#53]
we have CI script. However not link to travis now? cc @asajeffrey

**Comment by asajeffrey** [comment]
Good point. I enabled travis on my fork, but not on the origin. I don't have permissions to do this: @jdm or @aneeshusa do you know who does? https://travis-ci.org/servo/servo-warc-tests

**Comment by jdm** [comment]
I have enabled it on this repo.

**Comment by asajeffrey** [comment]
@jdm thanks!
