### ISSUE TITLE
Tracking issue for adding web archives for the Alexa top 10 sites

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo-warc-tests#8]
The Alexa top web sites are at: https://www.alexa.com/topsites. It would be nice to track performance data for more of these. The top 10 are:

 1. [x] Google.com
 2. [x] Youtube.com
 3. [x] Facebook.com
 4. [x] Baidu.com
 5. [x] Wikipedia.org
 6. [x] Reddit.com
 7. [x] Yahoo.com
 8. [x] Google.co.in
 9. [x] Qq.com
10. [X] Amazon.com

There are instructions for playing and recording web archives for Servo at https://github.com/servo/servo-warc-tests/blob/master/README.md.

The list of archives used for Servo performance testing is at https://github.com/servo/servo-warc-tests/blob/master/ARCHIVES

Please help out by recording web archives for us!

You can do that by going to one of the issues, and assigning yourself.

**Comment by tigercosmos** [comment]
I will pick `Facebook.com`

**Comment by Belwyyn** [comment]
I would like to do Youtube.com

**Comment by asajeffrey** [comment]
These are all done! Thanks to @aishpant, @Belwyyn, @javitoom, @LiHaoTan, @mcarolan, @sjoshid, @Succo, and @tigercosmos.
